<?php
$config['protocol']='smtp';  
$config['smtp_host']='ssl://smtp.googlemail.com';  
$config['smtp_port']='465';  
$config['smtp_timeout']='30';  
$config['smtp_user']='carlxaeron09@gmail.com';  
$config['smtp_pass']='';  
$config['charset']='utf-8';  
$config['newline']="\r\n";
?>
